= AWS Demo
include::_graphacademy_llm.adoc[]
:slug: aws-demo
:author: Ben Lackey
:category: genai-ecosystem
:tags: rag, demo, retrieval augmented generation, chatbot, edgar, sec filings, aws, bedrock
:neo4j-versions: 5.x
:page-pagination:
:page-product: aws-demo

This is a sample notebook and web application which shows how Amazon Bedrock and Titan can be used with Neo4j. It shows how to leverage generative AI to build and consume a knowledge graph in Neo4j.

The dataset we're using is from the SEC's EDGAR system.

The dataflow in this demo consists of two parts:

* Ingestion - we read the EDGAR files with Bedrock, extracting entities and relationships from them which is then ingested into a Neo4j database deployed from AWS Marketplace.
* Consumption - A user inputs natural language into a chat UI. Bedrock converts that to Neo4j Cypher which is run against the database. This flow allows non technical users to query the database.

== Installation

The Demo is available on GitHub: https://github.com/neo4j-partners/neo4j-generative-ai-aws

== Relevant Links
[cols="1,4"]
|===
| icon:github[] Code Repository | https://github.com/neo4j-partners/neo4j-generative-ai-aws[GitHub]
| APN Blog Post | https://aws.amazon.com/blogs/apn/leveraging-neo4j-and-amazon-bedrock-for-an-explainable-secure-and-connected-generative-ai-solution[Link]
| Demo Video | https://www.youtube.com/watch?v=nV3-KKEZnD4&list=PLG3nTnYVz3nya8Me9-Xj9vEuLYIOk03ba&index=11&t=14s[Link]
| Press Release | https://neo4j.com/press-releases/neo4j-aws-bedrock-integration[Link]
| Slides | https://docs.google.com/presentation/d/1pnJn1GV7tm6Gr-K-0bEB5TlkPRoDbqLTKkKjWdr3eZs/edit?usp=sharing[Link]
|===

== Videos & Tutorials

++++
<iframe width="640" height="480" src="https://www.youtube.com/embed/nV3-KKEZnD4" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++
