= Langchain4j
include::_graphacademy_llm.adoc[]
:slug: langchain4j
:author: Giuseppe Villani
:category: genai-ecosystem
:tags: langchain, langchain4j, java, neo4j, vector, index
:neo4j-versions: 5.x
:page-pagination:
:page-product: langchain4j

image::https://avatars.githubusercontent.com/u/132277850?v=4[width=400]

https://github.com/langchain4j[Langchain4j^] is a Java implementation of the langchain library.
It uses similar concepts, with Prompts, Chains, Transformers, Document Loaders, Agents, and more.

The Neo4j Integration makes the xref:vector-search.adoc[Neo4j Vector] index available in the Langchain4j library.

// https://github.com/langchain4j/langchain4j/tree/main/langchain4j-neo4j

== Installation

.pom.xml
[source,xml]
----
include::https://github.com/langchain4j/langchain4j-examples/raw/main/neo4j-example/pom.xml[lines=19..23]
----

== Functionality Includes

* Create vector index
* Populate nodes and vector index from documents
* Query vector index

== Documentation

An example is avalable at: https://github.com/langchain4j/langchain4j-examples/tree/main/neo4j-example

[source,java]
----
include::https://github.com/langchain4j/langchain4j-examples/raw/main/neo4j-example/src/main/java/Neo4jEmbeddingStoreExample.java[]
----

To create a Neo4jEmbeddingStore, we can write:
[source,java]
----
Neo4jEmbeddingStore embeddingStore = Neo4jEmbeddingStore.builder().<builderParameters>.build();



// we can use with `withBasicAuth`
.withBasicAuth(neo4jContainer.getBoltUrl(), USERNAME, ADMIN_PASSWORD)
// as alternative to driver:
Driver driver = GraphDatabase.driver(neo4jContainer.getBoltUrl(), AuthTokens.basic(USERNAME, ADMIN_PASSWORD));
----

Where `<builderParameters>` must have `dimension` and either `driver` or `withBasicAuth` parameters,
besides other optional ones.

Here is the complete builder list:

[options="header",cols="m,m,a"]
|===
| Key  | Default Value | Description
| driver | <required if withBasicAuth is not set> | the https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/Driver.html[Java Driver instance]
| withBasicAuth | <required if withBasicAuth is not set> | Creates an instance of Neo4jEmbeddingStore defining a https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/Driver.html[Java Driver instance], starting from `uri`, `user` and `password`
| dimension | <required> | the vector's dimension
| config | org.neo4j.driver.SessionConfig.forDatabase(`<databaseName>`) | the https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/SessionConfig.html[SessionConfig instance]
| label | "Document" | the label name 
| embeddingProperty | "embedding" | the embedding property name 
| idProperty | "id" | the id property name
| metadataPrefix | "" | the metadata prefix 
| textProperty | "text" | the text property name
| indexName | "vector" | the vector index name
| databaseName | "neo4j" | the database name
| retrievalQuery | "RETURN properties(node) AS metadata, node.`idProperty` AS `idProperty`, node.`textProperty` AS `textProperty`, node.`embeddingProperty` AS `embeddingProperty`, score" | the retrieval query
|===

=== Usage Examples

LangChain4j provides the following classes for Neo4j integration:
- `Neo4jEmbeddingStore`: Implements the EmbeddingStore interface, enabling storing and querying vector embeddings in a Neo4j database.
- `Neo4jText2CypherRetriever`: Supports retrieving original content associated with stored embeddings.

==== Neo4jEmbeddingStore

We can define an `Neo4jEmbeddingStore` with the required Java Driver instance and dimension and an optional label name in this way:

[source,java]
----
Driver driver = GraphDatabase.driver('<boltURL>', AuthTokens.basic('<username>', '<password>'));

Neo4jEmbeddingStore embeddingStore = Neo4jEmbeddingStore.builder()
    .withDriver(driver)
    .dimension(384)
    .label("CustomLabel")
    .build();
----

We can use `withBasicAuth` as an alternative to `driver` creation:
[source,java]
----
Neo4jEmbeddingStore embeddingStore = Neo4jEmbeddingStore.builder()
    .withBasicAuth('<boltURL>', '<username>', '<password>')
    .<otherBuilderParameters>
    .build();

/* instead of 
    Driver driver = GraphDatabase.driver('<boltURL>', AuthTokens.basic('<username>', '<password>'));
    Neo4jEmbeddingStore embeddingStore = Neo4jEmbeddingStore.builder()
        .withDriver(driver)
        .<otherBuilderParameters>
        .build()
*/
 
----

To add embeddings, execute:
[source,java]
----
Embedding embedding = embeddingModel.embed("embedText").content();
String id = embeddingStore.add(embedding);
// output: id of the embedding
----

To add embeddings with id:
[source,java]
----
String id = randomUUID();
Embedding embedding = embeddingModel.embed("embedText").content();
embeddingStore.add(id, embedding);
// output: id of the embedding
----

To add embeddings with segment:
[source,java]
----
TextSegment segment = TextSegment.from(randomUUID());
Embedding embedding = embeddingModel.embed(segment.text()).content();
String id = embeddingStore.add(embedding, segment);
// output: id of the embedding
----

To add embeddings with segment and metadata:
[source,java]
----
TextSegment segment = TextSegment.from(randomUUID(), Metadata.from(METADATA_KEY, "test-value"));
Embedding embedding = embeddingModel.embed(segment.text()).content();
String id = embeddingStore.add(embedding, segment);
// output: id of the embedding
----

Search embeddings:
[source,java]
----
Embedding embedding = embeddingModel.embed("embedText").content();
String id = embeddingStore.add(embedding);
final EmbeddingSearchRequest request = EmbeddingSearchRequest.builder()
        .queryEmbedding(embedding)
        .maxResults(10)
        .build();
final List<EmbeddingMatch<TextSegment>> relevant = embeddingStore.search(request).matches();
// output: list of embeddings
----

To search embeddings with `minScore`:

[source,java]
----
Embedding embedding = embeddingModel.embed("embedText").content();
String id = embeddingStore.add(embedding);
final EmbeddingSearchRequest request = EmbeddingSearchRequest.builder()
        .queryEmbedding(embedding)
        .maxResults(10)
        .minScore(0.15)
        .build();
final List<EmbeddingMatch<TextSegment>> relevant = embeddingStore.search(request).matches();
// output: list of embeddings
----

To search embeddings with segment with custom metadata prefix:
[source,java]
----
String metadataPrefix = "metadata.";
String labelName = "CustomLabelName";

Neo4jEmbeddingStore embeddingStore = Neo4jEmbeddingStore.builder()
        .withBasicAuth(neo4jContainer.getBoltUrl(), USERNAME, ADMIN_PASSWORD)
        .dimension(384)
        .metadataPrefix(metadataPrefix)
        .label(labelName)
        .indexName("customIdxName")
        .build();

String metadataCompleteKey = metadataPrefix + METADATA_KEY;
TextSegment segment = TextSegment.from(randomUUID(), Metadata.from(METADATA_KEY, "test-value"));
Embedding embedding = embeddingModel.embed(segment.text()).content();

String id = embeddingStore.add(embedding, segment);
// output: id of the embedding

final EmbeddingSearchRequest request = EmbeddingSearchRequest.builder()
        .queryEmbedding(embedding)
        .maxResults(10)
        .build();
final List<EmbeddingMatch<TextSegment>> relevant = embeddingStore.search(request).matches();
// output: list of embeddings
----

Search embeddings with segment with metadata and custom id prop:
[source,java]
----
String metadataPrefix = "metadata.";
String customIdProp = "customId ` & Prop ` To Sanitize";

Neo4jEmbeddingStore embeddingStore = Neo4jEmbeddingStore.builder()
        .withBasicAuth(neo4jContainer.getBoltUrl(), USERNAME, ADMIN_PASSWORD)
        .dimension(384)
        .metadataPrefix(metadataPrefix)
        .label("CustomLabelName")
        .indexName("customIdxName")
        .idProperty(customIdProp)
        .build();

String metadataCompleteKey = metadataPrefix + METADATA_KEY;

TextSegment segment = TextSegment.from(randomUUID(), Metadata.from(METADATA_KEY, "test-value"));
Embedding embedding = embeddingModel.embed(segment.text()).content();
String id = embeddingStore.add(embedding, segment);
// output: id of the embedding

final EmbeddingSearchRequest request = EmbeddingSearchRequest.builder()
                .queryEmbedding(embedding)
                .maxResults(10)
                .build();
final List<EmbeddingMatch<TextSegment>> relevant = embeddingStore.search(request).matches();
// output: list of embeddings
----

Add multiple embeddings
[source,java]
----
Embedding firstEmbedding = embeddingModel.embed("firstEmbedText").content();
Embedding secondEmbedding = embeddingModel.embed("secondEmbedText").content();
List<String> ids = embeddingStore.addAll(asList(firstEmbedding, secondEmbedding));
// output: list of the embedding ids

final EmbeddingSearchRequest request = EmbeddingSearchRequest.builder()
                .queryEmbedding(firstEmbedding)
                .maxResults(10)
                .build();
final List<EmbeddingMatch<TextSegment>> relevant = embeddingStore.search(request).matches();
// output: list of embeddings
----

Add multiple embeddings with segments
[source,java]
----
TextSegment firstSegment = TextSegment.from("firstText");
Embedding firstEmbedding = embeddingModel.embed(firstSegment.text()).content();
TextSegment secondSegment = TextSegment.from("secondText");
Embedding secondEmbedding = embeddingModel.embed(secondSegment.text()).content();

List<String> ids = embeddingStore.addAll(
        asList(firstEmbedding, secondEmbedding),
        asList(firstSegment, secondSegment)
); // output: list of the embedding ids

final EmbeddingSearchRequest request = EmbeddingSearchRequest.builder()
                .queryEmbedding(firstEmbedding)
                .maxResults(10)
                .build();
final List<EmbeddingMatch<TextSegment>> relevant = embeddingStore.search(request).matches();
// output: list of embeddings
----

==== Neo4jText2CypherRetriever
[source,java]
----
// create dataset
// CREATE (book:Book {title: 'Dune'})<-[:WROTE]-(author:Person {name: 'Frank Herbert'})");
Neo4jText2CypherRetriever retriever = Neo4jText2CypherRetriever.builder()
        .graph(graph)
        .chatLanguageModel(chatLanguageModel)
        .build();

Query query = new Query("Who is the author of the book 'Dune'?");

List<Content> contents = retriever.retrieve(query);

System.out.println(contents.get(0).textSegment().text()); 
// output: "Frank Herbert"
----


== Relevant Links
[cols="1,4"]
|===
| icon:user[] Authors | https://github.com/vga91[Giuseppe Villani from Neo4j Partner Larus^]
| icon:comments[] Community Support | https://community.neo4j.com/[Neo4j Online Community^]
| icon:github[] Data Repository | https://github.com/langchain4j/langchain4j/[GitHub]
| icon:github[] Issues | https://github.com/langchain4j/langchain4j/issues
// | icon:book[] Documentation |
|===

////

== Videos & Tutorials

Installation:
++++
<iframe width="320" height="180" src="" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

== Highlighted Articles

// link:https://medium.com/neo4j/....[article^]
////
