= Awesome Procedures On Cypher (APOC)
:docs: https://neo4j.com/docs/apoc/current
:docs-ext: https://neo4j.com/labs/apoc/5
:repo: https://github.com/neo4j/apoc
:repo-ext: https://github.com/neo4j-contrib/neo4j-apoc-procedures
:slug: apoc
:author: Michael Hunger
:category: labs
:tags: apoc, procedures, functions, utilities, extensions, libraries
:neo4j-versions: 3.5, 4.0, 4.1, 4.2, 4.3, 4.4, 5, AuraDB, AuraDS
:page-product: apoc

APOC (Awesome Procedures on Cypher) is an add-on library for Neo4j that provides hundreds of procedures and functions adding a lot of useful functionality.

[IMPORTANT]
Starting in *Neo4j 5 APOC core is now fully supported* by Neo4j product and engineering, with its own link:{docs}[documentation^] and link:{repo}[GitHub repository^]. APOC extended lives in the existing place as a pure open-source project with best effort releases and community support.

== APOC-Core

APOC has been split in two parts, a *Core* module which contains 450+ commonly used procedures and functions (most also available on Aura).
The additional *extended* module which contains 50 procedures that have external dependencies or are more experimental in nature (see below).

NOTE: Since Neo4j 5 *only the APOC-Core library* is officially supported by Neo4j product and engineering.

=== Installation

The APOC-Core library can be installed with a single click in Neo4j Desktop, can be enabled with the Docker Image, is available in all Neo4j Sandboxes and in Neo4j AuraDB and AuraDS.
In a Neo4j binary download, you can find the library in the `labs` folder, just copy it over to the `plugins` folder to make all non-restricted functionality available.

More detail in the {docs}/installation/[installation docs^].

=== Relevant Links

[cols="1,4"]
|===
| icon:user[] Authors | The Cypher Surface Team, many contributors, team of https://larus-ba.it/[Larus BA, Italy^]
| icon:gift[] Releases | {repo}/releases
| icon:github[] Source | {repo}
// | icon:book[] Developer Guide | https://neo4j.com/developer/neo4j-apoc/
| icon:book[] Docs | {docs}
| icon:book[] Aura Docs | https://neo4j.com/docs/aura/platform/apoc/
|===

=== Documentation

The library covers a lot of things, that's why we provide a link:{docs}/overview/[Overview of all APOC functions and procedures^].


* {docs}/import[Data Import^] and {docs}/export[Export^]
* {docs}/database-introspection[visual, tabular, structured Schema Information^]
* {docs}/misc[Utility functions for conversions, formatting, collections, maps and much more^]
* {docs}/cypher-execution[Dynamic Cypher Execution^]
* {docs}/graph-updates/data-creation[Dynamically Creating and Updating Nodes and Relationships^]
* {docs}/algorithms/path-finding-procedures[Advanced Path Finding Procedures^]
* {docs}/virtual[Virtual Nodes and Relationships for visualizing aggregation and more^]

== APOC-Extended

APOC Extended is an link:{repo-ext}[open-source project^], not maintained by Neo4j but the contributor community.
It contains procedures and functions for data integration, exporting data, cypher based procedures, natural-language-processing (NLP) and more.

NOTE: There is no official support, only best effort community support and maintenance.

=== Availability & Installation

For APOC Extended download the link:{repo-ext}/releases[appropriate release^] (same leading version numbers) for your Neo4j version into the `plugins` folder and restart the server.
You might need to enable restricted procedures or add an extra `$NEO4J_HOME/conf/apoc.conf` for configuration settings.

[NOTE]
APOC-Extended depends on the availability of APOC-Core, so you will need to ensure that the core-library is installed too.
Also, several of the procedures need additional libraries which can be also found in the releases pages.

// You can learn more in the https://neo4j.com/developer/neo4j-apoc/[APOC Developer Guide^].

=== Relevant Links

[cols="1,4"]
|===
| icon:user[] Authors | Michael Hunger, lots of internal and external contributors, especially the team from https://larus-ba.it/[Larus BA, Italy^] lead by Andrea Santurbano
| icon:gift[] Releases | {repo-ext}/releases
| icon:github[] Issues | {repo-ext}/issues
| icon:github[] Source | {repo-ext}
| icon:book[] Developer Guide | https://neo4j.com/developer/neo4j-apoc/
| icon:book[] Docs | {docs-ext}
// | icon:book[] Article |
// | icon:play-circle[] Example | A `:play apoc` browser guide shows some of the functionality.
|===

=== Documentation

* {docs-ext}/database-integration[Integration with other Databases^]
* {docs-ext}/nlp[Natural Language Processing (NLP)^]
* {docs-ext}/database-introspection[Database Introspection^]
* {docs-ext}/cypher-execution[Dynamic Cypher Execution^]
* {docs-ext}/cypher-execution/cypher-based-procedures-functions[Cypher Based Procedures and Functions^]
* {docs-ext}/graph-updates/uuid[Automatic UUIDs^]
* {docs-ext}/graph-updates/ttl[Data Eviction (TTL)^]
* {docs-ext}/graph-updates/graph-generators[Graph Generators^]
* {docs-ext}/export[Data Export^]


== Videos

We recorded the https://r.neo4j.com/apoc-videos[APOC Video Series^].
Here are the latest videos.

++++
<iframe width="320" height="180" src="https://www.youtube.com/embed/V1DTBjetIfk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<iframe width="320" height="180" src="https://www.youtube.com/embed/x34FuSLt0l8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<iframe width="320" height="180" src="https://www.youtube.com/embed/HvTvy4G9uJk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<iframe width="320" height="180" src="https://www.youtube.com/embed/0p4jBOXNgc8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQPqceydXxc6n9ocJgDur4Ri3bGq8RD2r_e-5-cWrti04v8Icrynf8A9H0XZwfsoAKig8cRrXQ-6T96/embed?start=false&loop=false&delayms=3000" frameborder="0" width="320" height="180" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
++++

== Available Content

* https://medium.com/neo4j/search?q=apoc[Medium Articles^]
* https://www.youtube.com/@neo4j/search?query=apoc[YouTube Livestreams & Videos^]
* https://medium.com/neo4j/efficient-neo4j-data-import-using-cypher-scripts-7d1268b0747[Efficient Neo4j Data Import Using Cypher-Scripts by Andrea Santurbano^]
* https://medium.com/neo4j/streaming-graph-loading-with-neo4j-and-apoc-triggers-188ed4dd40d5[Streaming Graph Loading with Neo4j and APOC Triggers by David Allen^]
* https://markhneedham.com/blog/tag/apoc/[APOC Articles by Mark Needham^]
