= Neo4j plugin for Liquibase
:docs: https://www.liquibase.org/
:!figure-caption:
:author: Florent Biville
:tags: migrations, refactoring, modeling
:neo4j-versions: 3.5, 4.0, 4.1, 4.2

image::logo.svg[]

Liquibase tracks, versions, and deploys database schema changes. This open source project helps millions of developers and teams around the world automate their database change process. 

The Liquibase Neo4j plugin allows you to track, version, and execute database changes against Neo4j.
Try the link:https://github.com/liquibase/liquibase-neo4j[Liquibase Neo4j plugin^] now!

To see these changes in your Neo4j graph database, please see our pages about link:https://neo4j.com/bloom[Neo4j Bloom], link:https://neo4j.com/developer/neo4j-browser/[Neo4j Browser], and link:https://neo4j.com/developer/tools-graph-visualization/[Graph Visualization].

== Features

* **Easy to use** Create your changes and Liquibase will automatically order and run them.
* **Powerful & Customizable** Easily fine tune deployments for specific environments using labels, contexts, and preconditions.
* **Works well with other tools** Works with most CI/CD tools you're already using. 
* **Rollbacks included** Undo database changes, either automatically or via custom rollback scripts.
* **Battle-tested** Liquibase is used by millions around the world since its creation in 2006.

Learn more about Liquibase at link:https://www.liquibase.com[Liquibase.com.]

== Documentation & Articles

View Documentation at link:https://docs.liquibase.com[Liquibase Docs.]


== Feedback

To submit feedback, please link:https://github.com/liquibase/liquibase-neo4j/issues[create an issue on Github.]

== Relevant Links


[cols="1,4"]
|===
| icon:user[] Authors | Florent Biville
| icon:gift[] Availability | link:https://github.com/liquibase/liquibase-neo4j/[Liquibase Neo4j plugin^]
| icon:github[] Issues | link:https://github.com/liquibase/liquibase-neo4j/issues[github.com/liquibase/liquibase-neo4j^]
| icon:documentation[] Liquibase Documentation | https://docs.liquibase.com
| icon:support[] Community Support | https://www.liquibase.org
| icon:start[] Get Started with Liquibase | https://www.liquibase.org/get-started/quickstart
|===
