= Neo4j plugin for Liquibase
:docs: https://www.liquibase.org/
:!figure-caption:
:author: Florent Biville
:tags: migrations, refactoring, modeling
:neo4j-versions: 3.5, 4.0, 4.1, 4.2

image::logo.svg[float=right, width=100, position="top"]

Liquibase is an open source project for tracking, managing and applying database schema changes.
This plugin allows you to define and execute changes against Neo4j, with all the features Liquibase supports.
Try the link:https://github.com/liquibase/liquibase-neo4j[Liquibase Neo4j plugin^] now!

== Features

* **Declarative** Declare the changes you want to run, let Liquibase run them!
* **Customizable** Easily change Liquibase execution defaults, express powerful conditions for specific environments.
* **Battle-tested** Liquibase has been created in 2006 and successfully used by many customers around the world ever since!

== Feedback

The Liquibase Neo4j plugin allows you to define and execute database changes.

For visualizing these changes in your Neo4j graph database, please see our pages about link:https://neo4j.com/bloom[Neo4j Bloom], link:https://neo4j.com/developer/neo4j-browser/[Neo4j Browser], and link:https://neo4j.com/developer/tools-graph-visualization/[Graph Visualization] in general.

To submit feedback, please link:https://github.com/liquibase/liquibase-neo4j/issues[create an issue on Github.]

== Relevant Links

[cols="1,4"]
|===
| icon:user[] Authors | Florent Biville
| icon:gift[] Availability | link:https://github.com/liquibase/liquibase-neo4j/[Liquibase Neo4j plugin^]
| icon:github[] Issues | link:https://github.com/liquibase/liquibase-neo4j/issues[github.com/liquibase/liquibase-neo4j^]
|===
